<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFxBt7x2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFxBt7x2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFxBt7x2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFxBt7x2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFxBt7x2\App_KernelDevDebugContainer([
    'container.build_hash' => 'FxBt7x2',
    'container.build_id' => '2f790eee',
    'container.build_time' => 1685222397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFxBt7x2');
